##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # cafe B-D: libctk-3-dev cafe-common
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - intltool
    - libayatana-appindicator3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libtool
    - make

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
